#Hard disable entire modules. Use at your own risk and don't ask for support if you use this. Write modid = false to disable modules
#Sat Jul 26 10:55:23 MDT 2025
villagersplus=true
betterarcheology=true
regions_unexplored=true
quark=true
twilightforest=true
