#Hard disable entire modules. Use at your own risk and don't ask for support if you use this. Write modid = false to disable modules
#Fri Aug 22 14:43:43 MDT 2025
villagersplus=true
regions_unexplored=true
quark=true
twilightforest=true
waystones=true
