#This file stores configuration options for Iris, such as the currently active shaderpack
#Sat Jul 26 10:55:05 MDT 2025
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
maxShadowRenderDistance=32
shaderPack=
enableShaders=true
